# Generated by Django 4.0.5 on 2022-07-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProducts',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ap_name', models.CharField(max_length=100)),
                ('ap_price', models.CharField(max_length=100)),
                ('ap_quantity', models.CharField(max_length=100)),
                ('ap_image', models.ImageField(default='', upload_to='app/static/media/images/')),
                ('ap_description', models.CharField(max_length=100)),
                ('ap_status', models.IntegerField(default=0)),
                ('ap_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_mobile', models.CharField(max_length=100)),
                ('ad_email', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
                ('ad_role', models.CharField(default='', max_length=100)),
                ('ad_status', models.IntegerField(default=0)),
                ('ad_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_name', models.CharField(max_length=100)),
                ('ct_image', models.CharField(max_length=100)),
                ('ct_weight', models.CharField(max_length=100)),
                ('ct_price', models.CharField(max_length=100)),
                ('ct_total_amount', models.IntegerField()),
                ('ct_ordered_by', models.CharField(max_length=100)),
                ('ct_status', models.CharField(max_length=100)),
                ('ct_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cg_name', models.CharField(max_length=100)),
                ('cg_status', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('or_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('or_name', models.CharField(max_length=100)),
                ('or_weight', models.CharField(max_length=100)),
                ('or_rate', models.CharField(max_length=100)),
                ('or_total_amount', models.CharField(max_length=100)),
                ('or_address', models.CharField(max_length=100)),
                ('or_ordered_by', models.CharField(max_length=100)),
                ('or_date', models.CharField(max_length=100)),
                ('or_transaction_id', models.CharField(max_length=100)),
                ('or_status', models.CharField(default=0, max_length=100)),
                ('or_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ps_or_id', models.CharField(max_length=100)),
                ('ps_product_name', models.CharField(max_length=100)),
                ('ps_image', models.CharField(max_length=100)),
                ('ps_weight', models.CharField(max_length=100)),
                ('ps_price', models.CharField(max_length=100)),
                ('ps_total_amt', models.CharField(max_length=100)),
                ('ps_date', models.CharField(max_length=100)),
                ('ps_status', models.CharField(max_length=100)),
                ('ps_user_name', models.CharField(max_length=100)),
                ('ps_user_email', models.CharField(max_length=100)),
                ('ps_vendor_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rg_name', models.CharField(max_length=100)),
                ('rg_mobile', models.CharField(max_length=100)),
                ('rg_email', models.CharField(max_length=100)),
                ('rg_password', models.CharField(max_length=100)),
                ('rg_address', models.CharField(default='', max_length=100)),
                ('rg_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rv_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rv_ap_id', models.CharField(max_length=100)),
                ('rv_name', models.CharField(max_length=100)),
                ('rv_email', models.CharField(max_length=100)),
                ('rv_message', models.CharField(max_length=100)),
                ('rv_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('sh_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sh_shipping_status', models.CharField(max_length=100)),
                ('sh_ordered_by', models.CharField(max_length=100)),
                ('sh_status', models.CharField(max_length=100)),
                ('sh_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('vp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vp_name', models.CharField(default='', max_length=100)),
                ('vp_price', models.CharField(default='', max_length=100)),
                ('vp_quantity', models.CharField(default='', max_length=100)),
                ('vp_image', models.ImageField(default='', upload_to='app/static/media/images/')),
                ('vp_description', models.CharField(default='', max_length=100)),
                ('vp_status', models.IntegerField(default=0)),
                ('vp_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
