# Generated by Django 4.1 on 2022-08-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cg_id',
            new_name='ca_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cg_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cg_status',
        ),
        migrations.AddField(
            model_name='category',
            name='ca_created_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='ca_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='ca_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
