# Generated by Django 4.1 on 2022-08-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cg_id_category_ca_id_remove_category_cg_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sc_category', models.CharField(default='', max_length=100)),
                ('sc_name', models.CharField(default='', max_length=100)),
                ('sc_status', models.CharField(default='', max_length=100)),
                ('sc_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
