# Generated by Django 4.1 on 2022-08-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='ap_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addproducts',
            name='ap_created_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addproducts',
            name='ap_role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addproducts',
            name='ap_sub_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
