# Generated by Django 4.1 on 2022-08-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_addproducts_ap_category_addproducts_ap_created_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
