# Generated by Django 4.2.3 on 2023-08-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('fp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fp_email', models.CharField(default='', max_length=100)),
                ('fp_otp', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
